# Generated by Django 2.1.7 on 2019-03-13 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bubbleapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
