# Generated by Django 2.1.7 on 2019-03-14 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bubbleapp', '0004_auto_20190314_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='add_date',
        ),
        migrations.AddField(
            model_name='hashtag',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date modified'),
            preserve_default=False,
        ),
    ]
