# Generated by Django 2.1.7 on 2019-03-18 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bubbleapp', '0005_auto_20190314_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='beer name')),
                ('abv', models.FloatField(verbose_name='Alcohol by volume')),
                ('isOrganic', models.BooleanField()),
                ('isRetired', models.BooleanField()),
                ('createDtae', models.DateField(verbose_name='Created')),
                ('updateDate', models.DateField(verbose_name='Updated')),
                ('glassName', models.CharField(max_length=200, verbose_name='Glass')),
                ('styleDescription', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('styleName', models.CharField(max_length=200)),
                ('shortname', models.CharField(max_length=200)),
                ('categoryName', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bubbleapp.Category')),
            ],
        ),
        migrations.AddField(
            model_name='beer',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bubbleapp.Style'),
        ),
    ]
