# Generated by Django 2.1.7 on 2019-03-18 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bubbleapp', '0006_auto_20190318_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beer',
            old_name='createDtae',
            new_name='createDate',
        ),
        migrations.RemoveField(
            model_name='style',
            name='shortname',
        ),
    ]
