# Generated by Django 2.1.7 on 2019-03-18 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bubbleapp', '0008_auto_20190318_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='abv',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Alcohol by volume'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='createDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='glassName',
            field=models.CharField(blank=True, max_length=200, verbose_name='Glass'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='isOrganic',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beer',
            name='isRetired',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beer',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bubbleapp.Style'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='styleDescription',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='updateDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='style',
            name='categoryName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bubbleapp.Category'),
        ),
        migrations.AlterField(
            model_name='style',
            name='styleName',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
