# Generated by Django 2.1.7 on 2019-03-18 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bubbleapp', '0010_auto_20190318_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='style',
            name='categoryName',
        ),
        migrations.AddField(
            model_name='beer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bubbleapp.Category'),
        ),
    ]
