# Generated by Django 2.1.7 on 2019-03-19 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bubbleapp', '0011_auto_20190318_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='date modified')),
                ('beerCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bubbleapp.Category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='date modified')),
                ('beerStyle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bubbleapp.Style')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
