# Generated by Django 2.1.7 on 2019-03-19 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bubbleapp', '0012_favouritecategory_favouritestyle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Hashtag',
        ),
    ]
