# Generated by Django 2.1.7 on 2019-03-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubbleapp', '0013_auto_20190319_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritecategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='favouritestyle',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
